name: "chatroom"
port: 8081
machine_id: 1
start_time: "2022-02-21"

log:
  level: "debug"
  filename: "char_room.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  root: "root"
  password: "cxs20030416"
  dbname: "chatroom"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  pool_size: 100
